version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0274"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql # Initialises DB automatically
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DISPLAY=${DISPLAY} # For GUI apps

volumes:
  postgres_data:
